import express from 'express';
import {sanitize} from '../../../middleware/sanitizer';
import chatGroupController from './chatGroup.controller';
import {validateBody, schemas} from '../../../middleware/validator';
import {Auth} from "../../../middleware/auth";
const chatGroupRouter = express.Router();
chatGroupRouter.route('/create').post(sanitize(), Auth, validateBody(schemas.createChatGroupSchema), chatGroupController.createChatGroup);
chatGroupRouter.route('/update').put(sanitize(), Auth, validateBody(schemas.updateChatGroupSchema), chatGroupController.updateChatGroup);
chatGroupRouter.route('/member_assign').post(sanitize(), Auth, validateBody(schemas.memberAssignGroupSchema), chatGroupController.memberAssignChatGroup);
chatGroupRouter.route('/get_details').get(sanitize(), Auth, chatGroupController.getAllGroupDetails);
chatGroupRouter.route('/message_send').post(sanitize(), Auth, validateBody(schemas.sendMessageGroupSchema), chatGroupController.sendMessageChatGroup);
chatGroupRouter.route('/message_get').get(sanitize(), Auth, chatGroupController.getAllGroupMessageDetails);
export default chatGroupRouter;
